---
- hosts: localhost
  roles:
    - { role: homebrew-installer }
    - { role: install-nodejs, become: yes }
    - { role: install-misc }
    - { role: install-zsh, become: yes }
    - { role: install-neovim, become: yes }
