---
- hosts: localhost
  vars:
      linuxbrew_path: /home/linuxbrew/.linuxbrew/bin
      src_setup_path: "{{ ansible_env.HOME }}/dev/BPS-Dev-Setup"
  environment:
    PATH: /opt/rh/devtoolset-8/root/usr/bin:{{ ansible_env.PATH }}
    MANPATH: "/opt/rh/devtoolset-8/root/usr/share/man:{{ lookup('env', 'MANPATH') }}"
    INFOPATH: "/opt/rh/devtoolset-8/root/usr/share/info:{{ lookup('env', 'INFOPATH') }}"
    PCP_DIR: /opt/rh/devtoolset-8/root
    PERL5LIB: "/opt/rh/devtoolset-8/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-8/root/usr/lib/perl5:/opt/rh/devtoolset-8/root//usr/share/perl5/vendor_perl:{{ lookup('env', 'PERL5LIB') }}"
    rpmlibdir_devtoolset8: /usr/lib64
    rpmlibdir_devtoolset8_lib_path: /usr/lib
    rpmlibdir32_devtoolset8: /opt/rh/devtoolset-8/root{{ ansible_env.rpmlibdir_devtoolset8_lib_path }}
    LD_LIBRARY_PATH: /opt/rh/devtoolset-8/root{{ ansible_env.rpmlibdir_devtoolset8 }}:{{ lookup('env', 'rpmlibdir32_devtoolset8') }}:{{ lookup( 'env', 'LD_LIBRARY_PATH') }}
    LD_LIBRARY_PATH: /opt/rh/devtoolset-8/root{{ ansible_env.rpmlibdir_devtoolset8 }}:{{ lookup('env', 'rpmlibdir32_devtoolset8') }}:/opt/rh/devtoolset-8/root{{ ansible_env.rpmlibdir_devtoolset8 }}/dyninst:{{ lookup('env', 'rpmlibdir32_devtoolset8') }}/dyninst:{{ lookup('env', 'LD_LIBRARY_PATH') }}
    pythonvers_devtoolset8: 2.6
    PYTHONPATH: /opt/rh/devtoolset-8/root/usr/lib64/python{{ ansible_env.pythonvers_devtoolset8 }}/site-packages:/opt/rh/devtoolset-8/root/usr/lib/python{{ lookup('env', 'pythonvers') }}/site-packages:{{ lookup('env', 'PYTHONPATH') }}
    PKG_CONFIG_PATH: /opt/rh/devtoolset-8/root/usr/lib64/pkgconfig:{{ lookup('env', 'PKG_CONFIG_PATH') }}
  roles:
    - { role: homebrew-installer }
    - { role: install-nodejs, become: yes }
    - { role: install-misc }
    - { role: install-zsh }
    - { role: install-neovim }
    - { role: install-cpptools }
    - { role: install-dotfiles }
    - { role: install-neovim-plugins }
