---
- hosts: localhost
  roles:
    - { role: homebrew-installer }
    - { role: install-nodejs, become: yes }
    - { role: install-misc }
    - { role: install-zsh }
    - { role: install-neovim }
    - { role: install-cpptools }
    - { role: install-dotfiles }
    - { role: install-neovim-plugins }
