- name: Install Neovim Dependencies
  become: yes
  yum:
    name:
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
    update_cache: yes
    state: present
- name: Download Neovim Source
  command: "git clone --recursive https://github.com/neovim/neovim {{ src_setup_path }}/neovim"
  args:
    creates: "{{ src_setup_path }}/neovim"
- name: Switch to Stable Neovim Source
  command: git checkout stable
  args:
    chdir: "{{ src_setup_path }}/neovim"
- name: Build Neovim Source
  command: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: "{{ src_setup_path }}/neovim"
- name: Install Neovim
  become: yes
  command: make install
  args:
    chdir: "{{ src_setup_path }}/neovim"
    creates: /usr/local/bin/nvim
- name: Setup Vim-Plug
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim"
    state: directory
    mode: '0755'
- name: Install Vim-Plug
  command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
