---
- hosts: localhost
  become: true
  tasks:
  - import_role:
      name: smbambling.scl
  - name: Install Linuxbrew prerequisites for Red Hat or CentOS
    yum:
      pkg:
        - bzip2-devel
        - curl
        - curl-devel
        - expat-devel
        - git
        - irb
        - m4
        - ncurses-devel
        - ruby
        - texinfo
        - zlib-devel
      update_cache: yes
      state: present
  - name: "Install Packages from Software Collections(SCL)"
    include_role:
      name: smbambling.scl
      tasks_from: packages
    vars:
      scl_packages:
        - {name: 'sclo-git212'}
        - {name: 'rh-ruby24'}
      scl_wrappers:
        - {collection: 'sclo-git212', command: 'git'}
        - {collection: 'rh-ruby24', command: 'ruby'}
- hosts: localhost
  tasks:
  - name: "Use Packages from Software Collections(SCL)"
    include_role:
      name: smbambling.scl
      tasks_from: packages
    vars:
      scl_wrappers:
        - {collection: 'sclo-git212', command: 'git'}
        - {collection: 'rh-ruby24', command: 'ruby'}
        - {collection: 'rh-python35', command: 'python'}
  - name: Check if Homebrew is already installed
    stat:
      path: /home/linuxbrew/.linuxbrew/bin/brew
    register: b
  - name: Install Homebrew
    script: install-homebrew.sh
    when: not b.stat.exists
- hosts: localhost
  become: true
  tasks:
  - name: Add Homebrew to $PATH.
    copy:
      dest: /etc/profile.d/bps-dev.sh
      content: 'PATH=/opt/rh/devtoolset-8/root/usr/bin:/home/linuxbrew/.linuxbrew/bin:$PATH'
  - name: Install NodeJS
    shell:
      cmd: curl -sL https://rpm.nodesource.com/setup_11.x | sudo bash -
  - name: Install Yarn
    shell:
      cmd: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
  - name: Install Yarn/NodeJS
    yum:
      pkg:
        - nodejs
        - yarn
      update_cache: yes
      state: present
- hosts: localhost
  tasks:
  - name: Install Pyenv(Python)
    shell:
      cmd: curl https://pyenv.run | bash
    args:
      creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
  - name: Install Rustup(Rust)
    shell:
      cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    args:
      creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
- hosts: localhost
  become: true
  tasks:
  - name: Install Zsh
    script: install-zsh.sh
    args:
      creates: /usr/local/bin/zsh
